#!/usr/bin/env python

import sys

from gi.repository import GLib

import btcon
from hashutils import bintohex, hextobin

if __name__ == '__main__':
    address = (sys.argv[1], int(sys.argv[2]))
    infohash = hextobin(sys.argv[3])

    m = GLib.MainLoop()

    def state_changed_cb(con, state):
        if state == btcon.BTConnection.STATE_CLOSED:
            GLib.idle_add(m.quit)

    def metadata_changed_cb(con):
        print('Name: {}'.format(con.metadata['name'].decode('utf-8')))

    def progress_changed_cb(con):
        print('Have: {}/{}'.format(con.peer_progress, con.piece_count))
        if con.peer_progress == con.piece_count:
            GLib.idle_add(con.close)

    c = btcon.BTConnection(infohash)
    c.connect('state-changed', state_changed_cb)
    c.connect('metadata-changed', metadata_changed_cb)
    c.connect('peer-progress-changed', progress_changed_cb)
    c.open(address)

    m.run()
