#!/usr/bin/env python

import datetime
import lpd
from hashutils import bintohex


if __name__ == '__main__':
    s = lpd.LPDSocket()

    running = True
    while running:
        try:
            data, sender = s.recv_announce()
            now = datetime.datetime.now()
            if data is not None:
                infohash, port = data
                print('{} {!r}: Infohash: {}, Port: {}'.format(now, sender, bintohex(infohash), port))
            else:
                print('{} {!r}: Invalid announce.'.format(now, sender))
        except KeyboardInterrupt:
            running = False

    s.close()
